import { 
  Vehicle, 
  Customer, 
  Invoice, 
  CashTransaction, 
  DamagePoint,
  MerchantSettings,
  TextTemplate,
  OperationDocument,
  ServiceBasisCategory,
  ServiceSubcategory
} from './types';
import { INITIAL_COMPANY_DOCUMENTS } from './data/companyDocumentsData';

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    brand: 'BMW',
    model: '320d xDrive M Sport',
    variant: 'Touring Aut. Laser Head-Up Pano',
    vin: 'WBA31AY080FK92184',
    firstRegistration: '05/2023',
    mileage: 28400,
    powerKw: 140,
    powerPs: 190,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    color: 'Mineralgrau Metallic',
    purchasePrice: 29800,
    sellingPrice: 35900,
    taxType: 'diff_25a',
    status: 'verfuegbar',
    daysInStock: 14,
    createdAt: '2026-08-03T10:15:00.000Z',
    location: 'Filiale Berlin-Spandau',
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['M Sportpaket', 'Laserlicht', 'Head-Up Display', 'Panoramadach', 'Harman/Kardon Sound', 'Anhängerkupplung'],
    showInWebShowroom: true,
    showroomBadge: 'Top Angebot',
    showroomShowMechanical: true,
    showroomShowBodywork: true,
    showroomShowFeatures: true,
    showroomHighlighted: true,
    showroomCustomNote: 'Lückenlos BMW-scheckheftgepflegt, Nichtraucherfahrzeug mit DEKRA Siegel und 12 Monaten Garantie.',
    conditionMechanical: {
      engine: 'Einwandfrei, voller Ladedruck, kein Ölverlust (Trocken)',
      transmission: '8-Gang Steptronic schaltet butterweich',
      brakesTires: 'Bremsen vorn 85%, hinten 80%, Michelin Pilot Sport',
      tuvDate: '2027-05',
      serviceHistory: true,
      lastService: '05/2026 bei 26.100 km (Große Inspektion bei BMW)'
    },
    conditionVisual: {
      paintCondition: 'Exzellenter Zustand, Keramikversiegelung, makellos',
      interiorCondition: 'Alcantara/Sensatec wie neu, keine Abnutzungen',
      accidentFree: true,
      damagesNotes: 'Keine Vorschäden, Originallackierung rundum',
      paintThicknessUm: 115
    }
  },
  {
    id: 'veh-2',
    brand: 'Mercedes-Benz',
    model: 'C 300 e T-Modell AMG Line',
    variant: 'EQ-Power Night-Paket Widescreen',
    vin: 'WDD2052531F894102',
    firstRegistration: '11/2022',
    mileage: 34100,
    powerKw: 235,
    powerPs: 320,
    fuelType: 'Plug-in-Hybrid',
    transmission: 'Automatik',
    color: 'Obsidianschwarz Metallic',
    purchasePrice: 33500,
    sellingPrice: 39800,
    taxType: 'standard_19',
    status: 'verfuegbar',
    daysInStock: 8,
    createdAt: '2026-08-09T14:30:00.000Z',
    location: 'Hauptstandort Mitte',
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['AMG Line', 'Night-Paket', 'Burmester Sound', '360° Kamera', 'Distronic Plus', 'Keyless-Go'],
    showInWebShowroom: true,
    showroomBadge: 'MwSt. 19% Ausweisbar',
    showroomShowMechanical: true,
    showroomShowBodywork: true,
    showroomShowFeatures: true,
    showroomHighlighted: true,
    showroomCustomNote: 'Ideal für Gewerbekunden (Leasing/Finanzierung möglich) mit 19% MwSt. Ausweis. Hochvolt-Batterie mit 100% Kapazität.',
    conditionMechanical: {
      engine: 'Hybrid-Antriebsstrang & E-Motor geprüft ohne Fehler',
      transmission: '9G-TRONIC Automatikgetriebe perfekt',
      brakesTires: 'Bremsanlage 90% Belagstärke, Reifen 6.5mm Profil',
      tuvDate: '2026-11',
      serviceHistory: true,
      lastService: '11/2025 bei 29.800 km'
    },
    conditionVisual: {
      paintCondition: 'Sehr gepflegter Erstbesitz, Tiefenglanz',
      interiorCondition: 'Artico/Dinamica schwarz, tierfrei',
      accidentFree: true,
      damagesNotes: 'Keine Beulen, keine Kratzer',
      paintThicknessUm: 120
    }
  },
  {
    id: 'veh-3',
    brand: 'Audi',
    model: 'A6 Avant 50 TDI quattro',
    variant: 'S line Matrix Luftfederung HD-Matrix',
    vin: 'WAUZZZF26MN048291',
    firstRegistration: '03/2021',
    mileage: 62000,
    powerKw: 210,
    powerPs: 286,
    fuelType: 'Diesel',
    transmission: 'Automatik',
    color: 'Daytonagrau Perleffekt',
    purchasePrice: 38000,
    sellingPrice: 44500,
    taxType: 'diff_25a',
    status: 'reserviert',
    daysInStock: 22,
    createdAt: '2026-07-26T11:00:00.000Z',
    location: 'Hauptstandort Mitte',
    imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['S line Sportpaket', 'HD Matrix-LED', 'Adaptive Air Suspension', 'Virtual Cockpit Plus', 'Standheizung'],
    showInWebShowroom: true,
    showroomBadge: 'Reserviert',
    showroomShowMechanical: true,
    showroomShowBodywork: true,
    showroomShowFeatures: true,
    showroomHighlighted: false,
    conditionMechanical: {
      engine: 'V6 TDI 3.0 Kraftvoller Durchzug, lückenlos bei Audi gewartet',
      transmission: 'Tiptronic 8-Stufen Allradantrieb',
      brakesTires: 'Neue Bremsen rundum vor 4.000 km erneuert',
      tuvDate: '2026-03',
      serviceHistory: true,
      lastService: '03/2026 bei 58.000 km'
    },
    conditionVisual: {
      paintCondition: 'Guter Allgemeinzustand mit leichten altersgemäßen Steinschlägen',
      interiorCondition: 'Valcona-Leder S-Prägung, sehr gepflegt',
      accidentFree: true,
      damagesNotes: 'Unfallfrei gem. Lackschichtenmessung',
      paintThicknessUm: 110
    }
  },
  {
    id: 'veh-4',
    brand: 'Volkswagen',
    model: 'Golf VIII GTI Clubsport',
    variant: '2.0 TSI DSG Akrapovic DCC 19 Zoll',
    vin: 'WVWZZZCDZMW189201',
    firstRegistration: '09/2022',
    mileage: 19500,
    powerKw: 221,
    powerPs: 300,
    fuelType: 'Benzin',
    transmission: 'Doppelkupplung',
    color: 'Pure White',
    purchasePrice: 28500,
    sellingPrice: 34900,
    taxType: 'standard_19',
    status: 'verfuegbar',
    daysInStock: 5,
    createdAt: '2026-08-12T09:20:00.000Z',
    location: 'Filiale Berlin-Spandau',
    imageUrl: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['DCC Fahrwerk', 'Akrapovic Titan-Auspuff', 'IQ.Light Matrix', '19" Estoril Felgen', 'Discover Pro'],
    showInWebShowroom: true,
    showroomBadge: 'Neu Eingetroffen',
    showroomShowMechanical: true,
    showroomShowBodywork: true,
    showroomShowFeatures: true,
    showroomHighlighted: true,
    showroomCustomNote: 'Traumzustand! Werksgarantie bis 09/2027, Akrapovic Titan-Sportabgasanlage ab Werk.',
    conditionMechanical: {
      engine: '2.0 TSI 300 PS EA888 Gen 4, top Zustand',
      transmission: '7-Gang DSG mit Vorderachs-Differenzialsperre',
      brakesTires: 'GTI Hochleistungsbremse 95%, Bridgestone Potenza 7mm',
      tuvDate: '2027-09',
      serviceHistory: true,
      lastService: '08/2026 bei 18.200 km (VW Service)'
    },
    conditionVisual: {
      paintCondition: 'Neuwertiger Glanz, kein Steinschlag',
      interiorCondition: 'Top-Sportsitze Clubsport, unberührt',
      accidentFree: true,
      damagesNotes: 'Keine Nachlackierungen',
      paintThicknessUm: 118
    }
  },
  {
    id: 'veh-5',
    brand: 'Porsche',
    model: 'Taycan 4S Cross Turismo',
    variant: 'Performance-Batterie Plus Panorama Bose',
    vin: 'WP0ZZZY1ZMSA48910',
    firstRegistration: '08/2022',
    mileage: 21300,
    powerKw: 420,
    powerPs: 571,
    fuelType: 'Elektro',
    transmission: 'Automatik',
    color: 'Kreide Uni',
    purchasePrice: 72000,
    sellingPrice: 84900,
    taxType: 'standard_19',
    status: 'aufbereitung',
    daysInStock: 3,
    createdAt: '2026-08-14T16:45:00.000Z',
    location: 'Premium Showroom Charlottenburg',
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80',
    images: [
      'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?auto=format&fit=crop&w=1200&q=80'
    ],
    features: ['Performance-Batterie Plus', 'Bose Surround', 'Hinterachslenkung', 'Sport Chrono Paket', '21" Cross Turismo Räder'],
    showInWebShowroom: true,
    showroomBadge: 'Porsche Approved',
    showroomShowMechanical: true,
    showroomShowBodywork: true,
    showroomShowFeatures: true,
    showroomHighlighted: true,
    showroomCustomNote: 'Porsche Approved Garantie bis 08/2027. 93.4 kWh Batterie (SoH 98.7%). 1. Hand unfallfrei.',
    conditionMechanical: {
      engine: 'Dual-Motor Allradantrieb 571 PS Overboost, Porsche 111-Punkte Check bestanden',
      transmission: '2-Gang Getriebe an der Hinterachse',
      brakesTires: 'Porsche Surface Coated Brake (PSCB) 90%',
      tuvDate: '2027-08',
      serviceHistory: true,
      lastService: '08/2026 im Porsche Zentrum Berlin'
    },
    conditionVisual: {
      paintCondition: 'Sonderfarbe Kreide, Steinschlagschutzfolie auf Vorderwagen',
      interiorCondition: 'Lederausstattung schwarz/kreide, Neuzustand',
      accidentFree: true,
      damagesNotes: 'Werkszustand unfallfrei',
      paintThicknessUm: 125
    }
  },
  {
    id: 'veh-6',
    brand: 'Cupra',
    model: 'Formentor VZ 2.0 TSI 4Drive',
    variant: 'Brembo Schalensitze Beats 19" Copper',
    vin: 'VSSZZZKMZNR081923',
    firstRegistration: '04/2023',
    mileage: 15800,
    powerKw: 228,
    powerPs: 310,
    fuelType: 'Benzin',
    transmission: 'Doppelkupplung',
    color: 'Petrol Blue Matt',
    purchasePrice: 27900,
    sellingPrice: 33400,
    taxType: 'diff_25a',
    status: 'verkauft',
    daysInStock: 29,
    createdAt: '2026-07-19T08:30:00.000Z',
    location: 'Hauptstandort Mitte',
    imageUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    features: ['Brembo Bremsanlage', 'BeatsAudio', 'CUPRA Schalensitze Leder Petrol Blau', 'Top View 360°']
  }
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    type: 'B2B',
    name: 'Dr. Michael Schultze',
    companyName: 'Schultze & Partner Immobilien GmbH',
    salutation: 'Firma',
    email: 'm.schultze@schultze-immo.de',
    phone: '+49 30 8892100',
    street: 'Kurfürstendamm 194',
    city: 'Berlin',
    postalCode: '10707',
    country: 'Deutschland',
    vatId: 'DE 294819201',
    taxNumber: '27/451/08912',
    purchasesCount: 4,
    totalSpent: 168400,
    lastContact: '14.08.2026',
    notes: 'Bevorzugt Firmenleasing & Vorsteuerabzug (§ 19%). Fuhrparkbetreuung.'
  },
  {
    id: 'cust-2',
    type: 'B2C',
    name: 'Sarah Lindemann',
    salutation: 'Frau',
    email: 's.lindemann@berlin-mail.de',
    phone: '+49 171 4981290',
    street: 'Schönhauser Allee 74',
    city: 'Berlin',
    postalCode: '10437',
    country: 'Deutschland',
    purchasesCount: 1,
    totalSpent: 35900,
    lastContact: '12.08.2026',
    notes: 'Kaufinteressentin BMW 320d. Baranzahlung und Rest per Überweisung.'
  },
  {
    id: 'cust-3',
    type: 'B2B',
    name: 'Thomas Bergmann',
    companyName: 'Bergmann Logistik & Transport KG',
    salutation: 'Firma',
    email: 'fuhrpark@bergmann-logistik.de',
    phone: '+49 30 5519820',
    street: 'Industriestraße 12-14',
    city: 'Potsdam',
    postalCode: '14482',
    country: 'Deutschland',
    vatId: 'DE 198471203',
    taxNumber: '046/182/09123',
    purchasesCount: 6,
    totalSpent: 215000,
    lastContact: '09.08.2026',
    notes: 'Regelmäßiger Abnehmer von Kombis und Nutzfahrzeugen.'
  },
  {
    id: 'cust-4',
    type: 'B2C',
    name: 'Alexander Weber',
    salutation: 'Herr',
    email: 'alex.weber@web.de',
    phone: '+49 176 8920194',
    street: 'Kantstraße 42',
    city: 'Berlin',
    postalCode: '10625',
    country: 'Deutschland',
    purchasesCount: 2,
    totalSpent: 48900,
    lastContact: '02.08.2026',
    notes: 'Gebrauchtwagen-Kunde, Differenzbesteuerung gewünscht.'
  },
  {
    id: 'cust-5',
    type: 'B2C',
    name: 'Elena Rostova',
    salutation: 'Frau',
    email: 'elena.rostova@gmx.net',
    phone: '+49 152 3891044',
    street: 'Clayallee 180',
    city: 'Berlin',
    postalCode: '14195',
    country: 'Deutschland',
    purchasesCount: 1,
    totalSpent: 84900,
    lastContact: '15.08.2026',
    notes: 'Probefahrt Porsche Taycan vereinbart mit rotem Kennzeichen.'
  }
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'RE-2026-0842',
    invoiceCategory: 'rechnung',
    documentType: 'rechnung',
    date: '14.08.2026',
    dueDate: '28.08.2026',
    kundeId: 'cust-4',
    customerName: 'Schultze & Partner Immobilien GmbH',
    customerType: 'B2B',
    customerStreet: 'Friedrichstraße 180',
    customerPostalCode: '10117',
    customerCity: 'Berlin',
    customerPhone: '+49 30 209040',
    customerEmail: 'fuhrpark@schultze-partner.de',
    vehicleTitle: 'Mercedes-Benz C 300 e T-Modell AMG Line',
    vin: 'WDD2052531F894102',
    amountNet: 33445.38,
    taxAmount: 6354.62,
    amountGross: 39800.00,
    amountPaid: 39800.00,
    taxType: 'standard_19',
    status: 'bezahlt',
    paymentMethod: 'Überweisung',
    payments: [
      {
        id: 'pmt-1',
        amount: 39800.00,
        paymentMethod: 'Banküberweisung',
        date: '15.08.2026',
        receiptNumber: 'BK-2026-088',
        recordedBy: 'M. Mustermann',
        notes: 'Vollständige Kaufpreisüberweisung Commerzbank'
      }
    ]
  },
  {
    id: 'inv-2',
    invoiceNumber: 'RE-2026-0841',
    invoiceCategory: 'rechnung',
    documentType: 'rechnung',
    date: '12.08.2026',
    dueDate: '26.08.2026',
    kundeId: 'cust-2',
    customerName: 'Sarah Lindemann',
    customerType: 'B2C',
    customerStreet: 'Bergmannstraße 19',
    customerPostalCode: '10961',
    customerCity: 'Berlin',
    customerPhone: '+49 160 9988771',
    customerEmail: 'sarah.lindemann@web.de',
    vehicleTitle: 'BMW 320d xDrive M Sport',
    vin: 'WBA31AY080FK92184',
    amountNet: 35900.00,
    taxAmount: 0.00,
    amountGross: 35900.00,
    amountPaid: 15000.00,
    taxType: 'diff_25a',
    status: 'teilbezahlt',
    paymentMethod: 'Überweisung',
    payments: [
      {
        id: 'pmt-2',
        amount: 15000.00,
        paymentMethod: 'Banküberweisung',
        date: '13.08.2026',
        receiptNumber: 'BK-2026-089',
        recordedBy: 'S. Becker',
        notes: 'Anzahlung Überweisung (Restfälligkeit bei Übergabe)'
      }
    ]
  },
  {
    id: 'inv-3',
    invoiceNumber: 'EXP-2026-0044',
    invoiceCategory: 'eu_export',
    documentType: 'eu_export',
    date: '11.08.2026',
    dueDate: '25.08.2026',
    kundeId: 'cust-5',
    customerName: 'Autocentrum Praha s.r.o.',
    customerType: 'B2B',
    customerStreet: 'Vinohradská 142',
    customerPostalCode: '13000',
    customerCity: 'Prag (Tschechien)',
    customerPhone: '+420 221 550 110',
    customerEmail: 'import@autocentrum-praha.cz',
    vehicleTitle: 'Porsche Taycan 4S Performance Plus',
    vin: 'WP0ZZZY1ZMSA48910',
    amountNet: 89900.00,
    taxAmount: 0.00,
    amountGross: 89900.00,
    amountPaid: 0.00,
    taxType: 'standard_19',
    status: 'offen',
    paymentMethod: 'Überweisung',
    notes: 'Steuerfreie innergemeinschaftliche Lieferung gem. § 4 Nr. 1b i.V.m. § 6a UStG. USt-IdNr.: CZ28941029'
  },
  {
    id: 'inv-4',
    invoiceNumber: 'KV-2026-0319',
    invoiceCategory: 'kaufvertrag',
    documentType: 'kaufvertrag',
    date: '10.08.2026',
    dueDate: '10.08.2026',
    customerName: 'Alexander Weber',
    customerType: 'B2C',
    customerStreet: 'Kurfürstendamm 88',
    customerPostalCode: '10707',
    customerCity: 'Berlin',
    customerPhone: '+49 172 8844221',
    customerEmail: 'alex.weber@berlin.de',
    vehicleTitle: 'Cupra Formentor VZ 2.0 TSI 4Drive',
    vin: 'VSSZZZKMZNR081923',
    amountNet: 33400.00,
    taxAmount: 0.00,
    amountGross: 33400.00,
    amountPaid: 33400.00,
    taxType: 'kaufvertrag',
    status: 'bezahlt',
    paymentMethod: 'Bar',
    payments: [
      {
        id: 'pmt-4',
        amount: 33400.00,
        paymentMethod: 'Barzahlung',
        date: '10.08.2026',
        receiptNumber: 'KB-2026-135',
        recordedBy: 'M. Mustermann',
        notes: 'Vollständige Barzahlung bei Fahrzeugübergabe (Geldwäscheprüfung OK)'
      }
    ]
  },
  {
    id: 'inv-5',
    invoiceNumber: 'RE-2026-0839',
    invoiceCategory: 'rechnung',
    documentType: 'rechnung',
    date: '20.07.2026',
    dueDate: '03.08.2026',
    customerName: 'Dr. Michael Weber',
    customerType: 'B2C',
    customerStreet: 'Unter den Linden 42',
    customerPostalCode: '10117',
    customerCity: 'Berlin',
    customerPhone: '+49 171 4455889',
    customerEmail: 'm.weber@charite.de',
    vehicleTitle: 'Mercedes-Benz GLC 300 d 4MATIC Coupe',
    vin: 'W1N2533091F772184',
    amountNet: 48900.00,
    taxAmount: 0.00,
    amountGross: 48900.00,
    amountPaid: 0.00,
    taxType: 'diff_25a',
    status: 'offen',
    paymentMethod: 'Überweisung',
    mahnstufe: 1,
    lastMahnungDate: '08.08.2026',
    dunnings: [
      {
        id: 'dunn-1',
        level: 1,
        date: '08.08.2026',
        dueDate: '18.08.2026',
        fee: 0.00,
        interest: 0.00,
        totalClaim: 48900.00,
        notes: '1. Höfliche Zahlungserinnerung versendet per E-Mail & Post.',
        generatedAt: '2026-08-08T10:00:00.000Z'
      }
    ]
  },
  {
    id: 'inv-6',
    invoiceNumber: 'STORNO-RE-2026-0835',
    invoiceCategory: 'storno',
    documentType: 'rechnung',
    date: '06.08.2026',
    dueDate: '06.08.2026',
    customerName: 'Klaus Hoffmann Automobile',
    customerType: 'B2B',
    customerStreet: 'Industriestraße 12',
    customerPostalCode: '14482',
    customerCity: 'Potsdam',
    customerPhone: '+49 331 992211',
    customerEmail: 'klaus@hoffmann-auto.de',
    vehicleTitle: 'Storno zu RE-2026-0835 (Audi A4 Avant)',
    vin: 'WAUZZZF49HA110294',
    amountNet: -28900.00,
    taxAmount: 0.00,
    amountGross: -28900.00,
    amountPaid: -28900.00,
    taxType: 'diff_25a',
    status: 'storniert',
    paymentMethod: 'Überweisung',
    originalInvoiceNumber: 'RE-2026-0835',
    originalInvoiceId: 'inv-legacy-835',
    stornoDetails: {
      stornoNumber: 'STORNO-RE-2026-0835',
      stornoDate: '06.08.2026',
      reason: 'Vertragsrücktritt / Fehlende Finanzierungszusage der Kundenbank',
      refundMethod: 'Bank',
      refundAmount: 28900.00,
      originalInvoiceNumber: 'RE-2026-0835',
      originalInvoiceId: 'inv-legacy-835',
      notes: 'Rückabwicklung gem. § 355 BGB ordnungsgemäß verbucht.'
    }
  },
  {
    id: 'inv-7',
    invoiceNumber: 'GS-2026-0012',
    invoiceCategory: 'gutschrift',
    documentType: 'rechnung',
    date: '04.08.2026',
    dueDate: '04.08.2026',
    customerName: 'Sarah Lindemann',
    customerType: 'B2C',
    customerStreet: 'Bergmannstraße 19',
    customerPostalCode: '10961',
    customerCity: 'Berlin',
    customerPhone: '+49 160 9988771',
    customerEmail: 'sarah.lindemann@web.de',
    vehicleTitle: 'Gutschrift / Rechnungskorrektur zu RE-2026-0841',
    vin: 'WBA31AY080FK92184',
    amountNet: -1200.00,
    taxAmount: 0.00,
    amountGross: -1200.00,
    amountPaid: -1200.00,
    taxType: 'diff_25a',
    status: 'bezahlt',
    paymentMethod: 'Überweisung',
    originalInvoiceNumber: 'RE-2026-0841',
    originalInvoiceId: 'inv-2',
    gutschriftDetails: {
      gutschriftNumber: 'GS-2026-0012',
      gutschriftDate: '04.08.2026',
      reasonCategory: 'Preisminderung nach Mängelrüge',
      reasonText: 'Einvernehmliche Gutschrift wegen Nachlackierung Stoßstange hinten & Lackaufbereitung',
      refundMethod: 'Bank',
      amountNet: -1200.00,
      taxAmount: 0.00,
      amountGross: -1200.00,
      originalInvoiceNumber: 'RE-2026-0841',
      originalInvoiceId: 'inv-2'
    }
  },
  {
    id: 'inv-8',
    invoiceNumber: 'RE-2026-0840',
    invoiceCategory: 'rechnung',
    documentType: 'rechnung',
    date: '08.08.2026',
    dueDate: '22.08.2026',
    customerName: 'Bergmann Logistik & Transport KG',
    customerType: 'B2B',
    customerStreet: 'Am Westhafen 4',
    customerPostalCode: '13353',
    customerCity: 'Berlin',
    customerPhone: '+49 30 390881',
    customerEmail: 'dispo@bergmann-logistik.de',
    vehicleTitle: 'Audi A6 Avant 50 TDI quattro',
    vin: 'WAUZZZF26MN048291',
    amountNet: 44500.00,
    taxAmount: 0.00,
    amountGross: 44500.00,
    amountPaid: 0.00,
    taxType: 'diff_25a',
    status: 'entwurf',
    paymentMethod: 'Finanzierung'
  }
];

export const INITIAL_CASH_TRANSACTIONS: CashTransaction[] = [
  {
    id: 'cash-1',
    receiptNumber: 'KB-2026-142',
    timestamp: '15.08.2026 10:15',
    type: 'einnahme',
    account: 'Kasse',
    category: 'Fahrzeuganzahlung',
    description: 'Baranzahlung Kaufvertrag Cupra Formentor (Herr Weber)',
    amount: 1500.00,
    taxRate: '0% (§ 25a)',
    balanceAfter: 4850.00,
    recordedBy: 'M. Mustermann'
  },
  {
    id: 'cash-2',
    receiptNumber: 'KB-2026-141',
    timestamp: '14.08.2026 16:40',
    type: 'ausgabe',
    account: 'Kasse',
    category: 'Betriebsausgabe',
    description: 'Zulassungsgebühren Straßenverkehrsamt & Schilderprägung',
    amount: -145.50,
    taxRate: '19%',
    balanceAfter: 3350.00,
    recordedBy: 'S. Becker'
  },
  {
    id: 'cash-3',
    receiptNumber: 'KB-2026-140',
    timestamp: '14.08.2026 11:20',
    type: 'ausgabe',
    account: 'Kasse',
    category: 'Fahrzeugaufbereitung',
    description: 'Barauslage Innenraum-Tiefenreinigung Porsche Taycan',
    amount: -180.00,
    taxRate: '19%',
    balanceAfter: 3495.50,
    recordedBy: 'K. Schmidt'
  },
  {
    id: 'cash-4',
    receiptNumber: 'KB-2026-139',
    timestamp: '13.08.2026 14:00',
    type: 'transit',
    account: 'Kasse',
    category: 'Bankeinzahlung',
    description: 'Geldtransit Hauptkasse zur Commerzbank Geschäftskonto',
    amount: -5000.00,
    taxRate: '0%',
    balanceAfter: 3675.50,
    recordedBy: 'M. Mustermann'
  },
  {
    id: 'cash-5',
    receiptNumber: 'BK-2026-088',
    timestamp: '12.08.2026 14:15',
    type: 'einnahme',
    account: 'Bank',
    category: 'Fahrzeugverkauf Banküberweisung',
    description: 'Überweisung Kaufpreis Mercedes C 300 e (Schultze & Partner)',
    amount: 39800.00,
    taxRate: '19%',
    balanceAfter: 145000.00,
    recordedBy: 'M. Mustermann'
  },
  {
    id: 'cash-6',
    receiptNumber: 'KB-2026-138',
    timestamp: '12.08.2026 09:30',
    type: 'einnahme',
    account: 'Kasse',
    category: 'Barverkauf Zubehör',
    description: 'Verkauf Original BMW Gummifußmatten & Kofferraumwanne',
    amount: 185.00,
    taxRate: '19%',
    balanceAfter: 8675.50,
    recordedBy: 'S. Becker'
  },
  {
    id: 'cash-7',
    receiptNumber: 'KB-2026-137',
    timestamp: '11.08.2026 08:30',
    type: 'sturz',
    account: 'Kasse',
    category: 'Tagesabschluss (Z-Bon)',
    description: 'Kassensturz und Abstimmung Soll/Ist-Bestand ohne Differenz',
    amount: 0.00,
    taxRate: '0%',
    balanceAfter: 8490.50,
    recordedBy: 'M. Mustermann'
  }
];

export const INITIAL_DAMAGE_POINTS: DamagePoint[] = [
  {
    id: 'dmg-1',
    x: 48,
    y: 18,
    view: 'front',
    type: 'Steinschlag',
    severity: 'Leicht',
    description: 'Vereinzelte Steinschläge auf der vorderen Stoßstange'
  },
  {
    id: 'dmg-2',
    x: 72,
    y: 44,
    view: 'side_right',
    type: 'Kratzer',
    severity: 'Leicht',
    description: 'Oberflächlicher Kratzer am Radlauf hinten rechts (ca. 4cm)'
  },
  {
    id: 'dmg-3',
    x: 32,
    y: 65,
    view: 'rear',
    type: 'Delle',
    severity: 'Mittel',
    description: 'Kleine Parkdelle an der Ladekante des Heckstoßfängers'
  }
];

export const DEFAULT_MERCHANT_SETTINGS: MerchantSettings = {
  // 1. Persönliche Daten & Firma
  companyName: 'MaxFleet Autohandelsgruppe GmbH',
  responsiblePerson: 'Max Mustermann', // Inhaber / Vertretungsberechtigter Geschäftsführer
  legalForm: 'GmbH',
  commercialRegister: 'HRB 198421 B',
  registerCourt: 'Amtsgericht Charlottenburg (Berlin)',
  logoUrl: '',
  signatureUrl: '',
  signatureTitle: 'Inhaber & Geschäftsführung',

  // 2. Adresse (Haupt-Rechnungsadresse)
  street: 'Kurfürstendamm 210',
  postalCode: '10719',
  city: 'Berlin',
  country: 'Deutschland',

  // 3. Kontakt
  phone: '+49 30 8920100',
  mobile: '+49 171 4509122',
  email: 'info@maxfleet-gruppe.de',
  website: 'https://www.maxfleet-gruppe.de',

  // 4. Steuer & Zoll
  taxNumber: '27/451/09812',
  vatId: 'DE 319 824 550',
  eoriNumber: 'DE8941205',
  taxOffice: 'Finanzamt Charlottenburg',
  defaultTaxation: 'diff_25a',
  vatRate: 19.0,

  // 5. Bankverbindung
  bankName: 'Commerzbank AG Berlin',
  iban: 'DE89 1004 0000 0123 4567 89',
  bic: 'COBADEFFXXX',
  accountHolder: 'MaxFleet Autohandelsgruppe GmbH',

  // 6. Startkapital (Kasse & Bank)
  initialCashBalance: 5000.00,
  initialCashDate: '2026-08-01',
  initialCashRegistered: true,
  initialBankBalance: 145000.00,
  initialBankDate: '2026-08-01',
  initialBankRegistered: true,

  // Master-Zugangsdaten & Administrator-Sicherheit
  masterPassword: 'AdminMaster2026!',
  masterPin: '4892',
  adminUsername: 'admin.maxfleet',
  securityUpdatedAt: '2026-08-15T10:00:00.000Z',

  // 7. Zusätzliche Standorte
  additionalLocations: [
    {
      id: 'loc-1',
      name: 'Filiale Berlin-Spandau (Verkauf & Auslieferung)',
      type: 'Filiale',
      street: 'Nonnendammallee 42',
      postalCode: '13599',
      city: 'Berlin',
      country: 'Deutschland',
      contactPerson: 'Stefan Becker',
      phone: '+49 30 3345100',
      isMainInvoiceAddress: false,
      notes: 'Gebrauchtwagen-Zentrum & Kundenübergabe'
    },
    {
      id: 'loc-2',
      name: 'Zentrallager & Werkstattzentrum Ruhleben',
      type: 'Werkstatt',
      street: 'Freiheit 15',
      postalCode: '13597',
      city: 'Berlin',
      country: 'Deutschland',
      contactPerson: 'Klaus Schmidt',
      phone: '+49 30 3345120',
      isMainInvoiceAddress: false,
      notes: 'Aufbereitung, Smart Repair & DEKRA Stützpunkt'
    },
    {
      id: 'loc-3',
      name: 'Premium Showroom Kantstraße',
      type: 'Showroom',
      street: 'Kantstraße 110',
      postalCode: '10627',
      city: 'Berlin',
      country: 'Deutschland',
      contactPerson: 'Alexander von Berg',
      phone: '+49 30 8891040',
      isMainInvoiceAddress: false,
      notes: 'Exklusive Sportwagen & High-End SUVs'
    }
  ],

  // 8. Rote Nummernschilder
  redLicensePlates: [
    {
      id: 'plate-1',
      plateNumber: 'B-06124',
      validUntil: '2027-12-31',
      status: 'probefahrt',
      assignedDriver: 'Stefan Becker',
      vehicleAssigned: 'Porsche Taycan 4S (WP0ZZZY1Z...)',
      logbookNotes: 'Probefahrt Interessent Dr. Weber (Route Avus Süd)',
      lastUsed: '15.08.2026'
    },
    {
      id: 'plate-2',
      plateNumber: 'B-06891',
      validUntil: '2027-12-31',
      status: 'verfuegbar',
      assignedDriver: '-',
      vehicleAssigned: '-',
      logbookNotes: 'Im Tresor Hauptstandort Mitte bereit',
      lastUsed: '12.08.2026'
    },
    {
      id: 'plate-3',
      plateNumber: 'B-06904',
      validUntil: '2028-06-30',
      status: 'verfuegbar',
      assignedDriver: '-',
      vehicleAssigned: '-',
      logbookNotes: 'Filiale Spandau Werkstattüberführung',
      lastUsed: '10.08.2026'
    }
  ],

  // 9. Benutzerverwaltung
  users: [
    {
      id: 'usr-1',
      username: 'max.admin',
      name: 'Max Mustermann',
      email: 'm.mustermann@maxfleet-gruppe.de',
      role: 'Administrator',
      roleType: 'admin',
      status: 'Aktiv',
      password: 'AdminMaster2026!',
      pinCode: '4892',
      permissions: {
        canAccessSettings: true,
        canManageVehicles: true,
        canManageCustomers: true,
        canManageInvoices: true,
        canManageFinances: true
      },
      lastLogin: '15.08.2026 13:42',
      createdAt: '2026-01-10'
    },
    {
      id: 'usr-2',
      username: 's.becker',
      name: 'Stefan Becker',
      email: 's.becker@maxfleet-gruppe.de',
      role: 'Verkäufer',
      roleType: 'mitarbeiter',
      status: 'Aktiv',
      password: 'BeckerPass2026!',
      pinCode: '1122',
      permissions: {
        canAccessSettings: false,
        canManageVehicles: true,
        canManageCustomers: true,
        canManageInvoices: true,
        canManageFinances: false
      },
      lastLogin: '15.08.2026 11:15',
      createdAt: '2026-02-15'
    },
    {
      id: 'usr-3',
      username: 'k.schmidt',
      name: 'Klaus Schmidt',
      email: 'k.schmidt@maxfleet-gruppe.de',
      role: 'Werkstatt',
      roleType: 'mitarbeiter',
      status: 'Aktiv',
      password: 'SchmidtPass2026!',
      pinCode: '3344',
      permissions: {
        canAccessSettings: false,
        canManageVehicles: true,
        canManageCustomers: false,
        canManageInvoices: false,
        canManageFinances: false
      },
      lastLogin: '14.08.2026 16:30',
      createdAt: '2026-03-01'
    },
    {
      id: 'usr-4',
      username: 'm.wagner',
      name: 'Monika Wagner',
      email: 'buchhaltung@maxfleet-gruppe.de',
      role: 'Buchhaltung',
      roleType: 'mitarbeiter',
      status: 'Aktiv',
      password: 'WagnerPass2026!',
      pinCode: '5566',
      permissions: {
        canAccessSettings: false,
        canManageVehicles: true,
        canManageCustomers: true,
        canManageInvoices: true,
        canManageFinances: true
      },
      lastLogin: '15.08.2026 09:00',
      createdAt: '2026-03-12'
    }
  ],

  // 11. Web-Showroom & Online-Präsenz
  showroomSettings: {
    enabled: true,
    showroomTitle: 'MaxFleet Autohandelsgruppe – Digitaler Showroom',
    showroomSlogan: 'Geprüfte Premium-Gebrauchtwagen, Sportwagen & Dienstwagen mit DEKRA Siegel & Garantie',
    heroBgUrl: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1920&q=80',
    heroBgPreset: 'luxury_showroom',
    customDomain: 'www.maxfleet-autohaus.de',
    subdomainSlug: 'maxfleet-berlin',
    whatsappNumber: '+49 171 4509122',
    openingHours: {
      weekdays: 'Mo. - Fr.: 09:00 - 18:30 Uhr',
      saturday: 'Sa.: 10:00 - 15:00 Uhr',
      sunday: 'So.: Geschlossen (Schautag online 24/7)'
    },
    legalImpressum: {
      companyName: 'MaxFleet Autohandelsgruppe GmbH',
      representedBy: 'Geschäftsführer: Max Mustermann',
      streetAddress: 'Kurfürstendamm 210',
      zipCity: '10719 Berlin, Deutschland',
      phone: '+49 30 8920100',
      email: 'info@maxfleet-gruppe.de',
      registerCourt: 'Amtsgericht Charlottenburg (Berlin)',
      registerNumber: 'HRB 198421 B',
      vatId: 'DE 319 824 550',
      disclaimerText: 'Angaben gemäß § 5 DDG (Digitale-Dienste-Gesetz). Verbraucherinformation gem. Verordnung (EU) Nr. 524/2013: Zur Beilegung von Streitigkeiten steht die Europäische Online-Streitbeilegungsplattform zur Verfügung. Wir sind nicht verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.'
    },
    defaultShowMechanical: true,
    defaultShowBodywork: true,
    defaultShowFeatures: true,
    defaultShowVin: false,
    enableAiChatbot: true,
    aiChatbotWelcomeMessage: 'Hallo und herzlich willkommen bei der MaxFleet Autohandelsgruppe! Ich bin MAX, Ihr persönlicher digitaler Showroom-Berater. Wie kann ich Ihnen zu unseren Fahrzeugen, Zustand oder Preisen weiterhelfen?',
    dealerPreferredChatLanguage: 'de'
  },

  // 12. Selber gestalten (Service-Basis & Unterkategorien)
  serviceBases: [
    {
      id: 'srv-basis-1',
      name: 'Werkstatt & Mechanik',
      code: 'SRV-WERKSTATT',
      icon: 'Wrench',
      color: 'blue',
      description: 'Inspektionen, Reparaturen, Motor, Getriebe und Fahrwerksarbeiten',
      defaultTaxRate: '19%',
      orderIndex: 0,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-1-1',
          name: 'Große Inspektion (nach Herstellervorgabe)',
          code: 'INSP-GROSS',
          description: 'Vollumfängliche Inspektion inkl. aller Filter und Funktionsprüfung',
          defaultPrice: 380.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 180,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-1-2',
          name: 'Kleine Inspektion / Jahreswartung',
          code: 'INSP-KLEIN',
          description: 'Basis-Durchsicht, Sichtprüfung und Standardwartung',
          defaultPrice: 190.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 90,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-1-3',
          name: 'Ölwechsel-Service inkl. Filter & Vollsynthetiköl',
          code: 'SRV-OEL',
          description: 'Motorölwechsel mit Markenöl (5W-30 / 0W-20) und Ölfilter',
          defaultPrice: 149.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 45,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-1-4',
          name: 'Bremsen-Service (Scheiben & Beläge)',
          code: 'SRV-BREMSE',
          description: 'Erneuerung der Bremsbeläge und Bremsscheiben pro Achse',
          defaultPrice: 420.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 120,
          active: true,
          orderIndex: 3,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-1-5',
          name: 'Klimaanlagen-Wartung & Desinfektion (R134a / R1234yf)',
          code: 'SRV-KLIMA',
          description: 'Kältemittel absaugen, Dichtheitsprüfung, Neubefüllung & Ozonung',
          defaultPrice: 129.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 60,
          active: true,
          orderIndex: 4,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-1-6',
          name: 'Fehlerspeicher-Diagnose & OBD-Systemcheck',
          code: 'SRV-DIAGNOSE',
          description: 'Tiefendiagnose aller Steuergeräte und Protokollausdruck',
          defaultPrice: 49.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 30,
          active: true,
          orderIndex: 5,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-2',
      name: 'Fahrzeugaufbereitung & Detailing',
      code: 'SRV-AUFBEREITUNG',
      icon: 'Sparkles',
      color: 'emerald',
      description: 'Professionelle Innen- und Außenaufbereitung, Politur und Versiegelung',
      defaultTaxRate: '19%',
      orderIndex: 1,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-2-1',
          name: 'Komplett-Aufbereitung Verkauf (Innen & Außen)',
          code: 'AUFB-KOMPLETT',
          description: 'Handwäsche, 1-Stufen-Politur, Nasssaugen, Kunststoffpflege',
          defaultPrice: 280.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 240,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-2-2',
          name: 'Keramik-Lackversiegelung (High-End Longlife)',
          code: 'AUFB-KERAMIK',
          description: 'Lackkorrektur 3-stufig + 9H Keramik-Coating mit Langzeitschutz',
          defaultPrice: 650.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 360,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-2-3',
          name: 'Lederreinigung, Tönung & Imprägnierung',
          code: 'AUFB-LEDER',
          description: 'Tiefenreinigung des Ledergestühls, Farbauffrischung und UV-Schutz',
          defaultPrice: 160.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 120,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-2-4',
          name: 'Ozonbehandlung (Geruchsbeseitigung / Raucherfahrzeug)',
          code: 'AUFB-OZON',
          description: 'Hygienische Geruchsneutralisierung von Bakterien und Nikotin',
          defaultPrice: 89.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 180,
          active: true,
          orderIndex: 3,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-3',
      name: 'Smart Repair & Karosserie',
      code: 'SRV-SMARTREPAIR',
      icon: 'ShieldCheck',
      color: 'amber',
      description: 'Dellenentfernung, Spot-Lackierung und optische Instandsetzung',
      defaultTaxRate: '19%',
      orderIndex: 2,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-3-1',
          name: 'Dellendrücken ohne Lackieren (PDR)',
          code: 'SMART-DELLE',
          description: 'Hagelschaden- und Parkdellen-Beseitigung mit Hebeltechnik',
          defaultPrice: 95.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 60,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-3-2',
          name: 'Spot-Repair Beilackierung (Stoßfänger / Kotflügel)',
          code: 'SMART-LACK',
          description: 'Punktuelle Teillackierung bei Kratzern und Schrammen',
          defaultPrice: 185.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 150,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-3-3',
          name: 'Alufelgen-Aufbereitung (Bordsteinschäden)',
          code: 'SMART-FELGE',
          description: 'Glanzdrehen, Ausschleifen und CNC-Felgenreparatur pro Felge',
          defaultPrice: 120.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 90,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-4',
      name: 'TÜV / DEKRA & Gutachten',
      code: 'SRV-TUEV',
      icon: 'FileText',
      color: 'purple',
      description: 'Amtliche Hauptuntersuchung, § 21 Vollabnahmen und Wertgutachten',
      defaultTaxRate: '19%',
      orderIndex: 3,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-4-1',
          name: 'Hauptuntersuchung (HU) inkl. AU (TÜV / DEKRA neu)',
          code: 'TUEV-HU-AU',
          description: 'Amtliche Plakettenprüfung inkl. Abgasuntersuchung',
          defaultPrice: 155.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 45,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-4-2',
          name: 'Gebrauchtwagen-Zustandszertifikat (100-Punkte-Check)',
          code: 'TUEV-CHECK',
          description: 'Unabhängiges technisches Prüfprotokoll mit Siegel',
          defaultPrice: 120.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 60,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-4-3',
          name: 'Import-Vollabnahme & Datenblatt (§ 21 StVZO)',
          code: 'TUEV-VOLLABNAHME',
          description: 'Gutachten zur Erlangung einer deutschen Betriebserlaubnis',
          defaultPrice: 280.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 90,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-5',
      name: 'Zulassungsdienst & Logistik',
      code: 'SRV-ZULASSUNG',
      icon: 'Truck',
      color: 'cyan',
      description: 'Zulassung, Überführungskennzeichen, Ausfuhrdokumente & Fahrzeugtransport',
      defaultTaxRate: '19%',
      orderIndex: 4,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-5-1',
          name: 'KFZ-Zulassungsdienst (Regional inkl. Wunschkennzeichen & Schilder)',
          code: 'ZUL-REGIONAL',
          description: 'Komplette Behördenabwicklung, Euro-Kennzeichen und Grüne Plakette',
          defaultPrice: 140.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 120,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-5-2',
          name: 'Ausfuhr- / Zollkennzeichen (inkl. 15/30 Tage Versicherung & Zollabfertigung)',
          code: 'ZUL-EXPORT',
          description: 'Rote Ausfuhrkennzeichen für internationalen Export inkl. Versicherung',
          defaultPrice: 280.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 180,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-5-3',
          name: 'Kurzzeitkennzeichen (5-Tages-Überführung gelbes Band)',
          code: 'ZUL-KURZZEIT',
          description: 'Überführungskennzeichen mit Versicherung für Probefahrten und Transport',
          defaultPrice: 110.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 60,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-5-4',
          name: 'Fahrzeuglieferung bis Haustür (Deutschlandweit)',
          code: 'LOG-TRANSPORT',
          description: 'Sicherer Einzeltransport auf Autotransporter bis Wunschadresse',
          defaultPrice: 350.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 300,
          active: true,
          orderIndex: 3,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-6',
      name: 'Reifen & Räder Service',
      code: 'SRV-REIFEN',
      icon: 'Disc',
      color: 'rose',
      description: 'Saisonwechsel, Reifenmontage, Wuchten und Radeinlagerung',
      defaultTaxRate: '19%',
      orderIndex: 5,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-6-1',
          name: 'Saison-Radwechsel (4 Kompletträder umstecken)',
          code: 'RAD-WECHSEL',
          description: 'Räderwechsel inkl. Luftdruckkontrolle und Drehmoment-Nachzug',
          defaultPrice: 45.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 30,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-6-2',
          name: 'Reifenmontage & dynamisches Auswuchten (4 Reifen)',
          code: 'RAD-MONTAGE',
          description: 'Reifen auf Felgen aufziehen, neue Ventile und Laser-Auswuchtung',
          defaultPrice: 90.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 60,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-6-3',
          name: 'Räder-Einlagerungsgemeinschaft (1 Saison inkl. Radwäsche)',
          code: 'RAD-LAGER',
          description: 'Fachgerechte, trockene Reifeneinlagerung und Hochdruckreinigung',
          defaultPrice: 75.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 30,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    },
    {
      id: 'srv-basis-7',
      name: 'Garantie & Zusatzpakete',
      code: 'SRV-GARANTIE',
      icon: 'Shield',
      color: 'indigo',
      description: 'Gebrauchtwagengarantie, Mobilitätsschutz und Sonderausstattungen',
      defaultTaxRate: '19%',
      orderIndex: 6,
      active: true,
      createdAt: '2026-08-01T08:00:00.000Z',
      subcategories: [
        {
          id: 'sub-7-1',
          name: '12 Monate Premium-Gebrauchtwagengarantie (Intec / Real Garant)',
          code: 'GAR-12M',
          description: 'Komplettschutz auf Motor, Getriebe, Elektrik und Komfortsysteme',
          defaultPrice: 490.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 15,
          active: true,
          orderIndex: 0,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-7-2',
          name: '24 Monate Erweiterte Langzeitgarantie',
          code: 'GAR-24M',
          description: '2 Jahre Maximale Absicherung mit 100% Lohn- und Materialkostenübernahme',
          defaultPrice: 850.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 15,
          active: true,
          orderIndex: 1,
          createdAt: '2026-08-01T08:00:00.000Z'
        },
        {
          id: 'sub-7-3',
          name: 'Anhängerkupplung (AHK) Nachrüstung (abnehmbar/schwenkbar)',
          code: 'EXT-AHK',
          description: 'Einbau einer Marken-AHK inkl. 13-poligem fahrzeugspezifischen E-Satz',
          defaultPrice: 790.00,
          defaultTaxRate: '19%',
          estimatedDurationMinutes: 240,
          active: true,
          orderIndex: 2,
          createdAt: '2026-08-01T08:00:00.000Z'
        }
      ]
    }
  ],

  updatedAt: new Date().toISOString()
};

export const DEFAULT_SERVICE_BASES: ServiceBasisCategory[] = DEFAULT_MERCHANT_SETTINGS.serviceBases || [];

export const INITIAL_TEXT_TEMPLATES: TextTemplate[] = [
  // a) Begrüßungstexte / Kopfzeile (Welcome/Intro texts)
  {
    id: 'tpl-w-1',
    category: 'welcome',
    title: 'Standard-Rechnungskopf Begrüßung',
    content: 'Sehr geehrte Kundin, sehr geehrter Kunde, vielen Dank für Ihr Vertrauen in unser Autohaus. Nachfolgend stellen wir Ihnen das erworbene Fahrzeug wie vereinbart in Rechnung.',
    isDefault: true,
    orderIndex: 0,
    tags: ['Standard', 'B2C/B2B'],
    createdAt: '2026-08-01T10:00:00.000Z'
  },
  {
    id: 'tpl-w-2',
    category: 'welcome',
    title: 'Freundliche Partnerschaft & Gute Fahrt',
    content: 'Vielen Dank für den Kauf Ihres Fahrzeugs bei der MaxFleet Autohandelsgruppe. Wir freuen uns über die partnerschaftliche Zusammenarbeit und wünschen Ihnen allzeit gute und sichere Fahrt!',
    isDefault: false,
    orderIndex: 1,
    tags: ['Premium', 'Stammkunden'],
    createdAt: '2026-08-02T11:00:00.000Z'
  },
  {
    id: 'tpl-w-3',
    category: 'welcome',
    title: 'Kaufvertrag Abrechnung (Förmlich)',
    content: 'Im Rahmen des geschlossenen Kraftfahrzeug-Kaufvertrages berechnen wir Ihnen das folgende Neufahrzeug / Gebrauchtfahrzeug zur sofortigen Begleichung vor Fahrzeugübergabe.',
    isDefault: false,
    orderIndex: 2,
    tags: ['Förmlich', 'Export'],
    createdAt: '2026-08-03T12:00:00.000Z'
  },

  // b) Garantie- & Gewährleistungstexte / Haupttext (Body/Warranty texts)
  {
    id: 'tpl-b-1',
    category: 'warranty',
    title: 'Standard Verbraucher (B2C) 12 Monate Gewährleistung',
    content: '12 Monate gesetzliche Sachmängelhaftung für Verbraucher (B2C) ab dem Tag der Fahrzeugübergabe. Ausgenommen hiervon sind normaler betriebsbedingter Verschleiß, Bremsbeläge, Reifen sowie Mängel durch unsachgemäße Bedienung.',
    isDefault: true,
    orderIndex: 0,
    tags: ['B2C', 'Standard'],
    createdAt: '2026-08-01T10:05:00.000Z'
  },
  {
    id: 'tpl-b-2',
    category: 'warranty',
    title: 'Gewerbe / B2B Gewährleistungsausschluss gem. § 444 BGB',
    content: 'Verkauf an Gewerbetreibende / Unternehmer (B2B): Der Verkauf erfolgt unter vollständigem Ausschluss jeglicher Sachmängelhaftung, Garantie und Gewährleistung gem. § 444 BGB. Das Fahrzeug wurde besichtigt und zur Kenntnis genommen.',
    isDefault: false,
    orderIndex: 1,
    tags: ['B2B', 'Händlergeschäft'],
    createdAt: '2026-08-01T10:10:00.000Z'
  },
  {
    id: 'tpl-b-3',
    category: 'warranty',
    title: 'Inklusive 24 Monate Premium-Garantieversicherung',
    content: 'Im Kaufpreis enthalten ist eine 24-monatige Premium-Gebrauchtwagengarantie mit europaweiter Gültigkeit und Mobilitätsschutz gemäß den beiliegenden Garantiebedingungen des Garantiepartners.',
    isDefault: false,
    orderIndex: 2,
    tags: ['Garantie Plus', 'Zusatzschutz'],
    createdAt: '2026-08-02T14:00:00.000Z'
  },
  {
    id: 'tpl-b-4',
    category: 'warranty',
    title: 'Differenzbesteuerung § 25a UStG Hinweis',
    content: 'Gebrauchtgegenstände / Sonderregelung: Die Besteuerung erfolgt nach § 25a UStG (Differenzbesteuerung). Ein gesonderter Ausweis der Umsatzsteuer auf der Rechnung ist gesetzlich ausgeschlossen.',
    isDefault: false,
    orderIndex: 3,
    tags: ['Steuerhinweis', '§ 25a'],
    createdAt: '2026-08-03T09:30:00.000Z'
  },

  // c) Export- & Steuerklauseln (EU & Drittland)
  {
    id: 'tpl-e-1',
    category: 'export',
    title: 'EU-Export: § 4 Nr. 1b i.V.m. § 6a UStG (Reverse Charge)',
    content: 'Steuerfreie innergemeinschaftliche Lieferung gem. § 4 Nr. 1b i.V.m. § 6a UStG. Übergang der Steuerschuldnerschaft auf den Leistungsempfänger (Reverse Charge). Die Verbringung in das EU-Ausland wird versichert.',
    isDefault: true,
    orderIndex: 0,
    tags: ['EU-Export', 'Reverse Charge'],
    createdAt: '2026-08-01T10:20:00.000Z'
  },
  {
    id: 'tpl-e-2',
    category: 'export',
    title: 'Drittland-Export: § 4 Nr. 1a i.V.m. § 6 UStG (Ausfuhrlieferung)',
    content: 'Steuerfreie Ausfuhrlieferung in das Drittland gem. § 4 Nr. 1a i.V.m. § 6 UStG. Der Ausfuhrnachweis (elektronischer Ausgangsvermerk ATLAS) wird durch das zuständige Hauptzollamt erbracht.',
    isDefault: false,
    orderIndex: 1,
    tags: ['Drittland', 'Zoll / ATLAS'],
    createdAt: '2026-08-01T10:25:00.000Z'
  },
  {
    id: 'tpl-e-3',
    category: 'export',
    title: 'Gelangensbestätigung & Verbringungsnachweis',
    content: 'Export-Kaufvertrag & Gelangensbestätigung: Der Käufer verpflichtet sich zur unverzüglichen Rücksendung der vollständig unterzeichneten Gelangensbestätigung (Confirmation of Arrival) nach Ankunft des Fahrzeugs im Bestimmungsland.',
    isDefault: false,
    orderIndex: 2,
    tags: ['Gelangensbestätigung', 'Nachweis'],
    createdAt: '2026-08-02T16:00:00.000Z'
  }
];

export const INITIAL_OPERATIONS: OperationDocument[] = [
  {
    id: 'op-pf-1001',
    documentType: 'probefahrt',
    documentNumber: 'PF2608-1001',
    date: '15.08.2026',
    kundeId: 'cust-1',
    customer: {
      id: 'cust-1',
      type: 'B2C',
      name: 'Dr. Michael Weber',
      salutation: 'Herr',
      email: 'm.weber@charite.de',
      phone: '+49 171 4455889',
      street: 'Unter den Linden 42',
      city: 'Berlin',
      postalCode: '10117',
      country: 'Deutschland',
      idCardNumber: 'L82910482B',
      purchasesCount: 1,
      totalSpent: 89000,
      lastContact: '15.08.2026'
    },
    isManualCustomer: false,
    autoId: 'veh-5',
    vehicles: [
      {
        id: 'veh-item-1',
        vehicleId: 'veh-5',
        vin: 'WP0ZZZY1ZMSA48910',
        brand: 'Porsche',
        model: 'Taycan 4S',
        variant: 'Performance Plus Panoramadach Sport Chrono',
        firstRegistration: '09/2022',
        mileage: 18500,
        powerPs: 530,
        powerKw: 390,
        fuelType: 'Elektro',
        color: 'Kreide',
        listPrice: 89900,
        sellingPrice: 89900,
        discountAmount: 0,
        taxType: 'standard_19'
      }
    ],
    totalNet: 0,
    totalTax: 0,
    totalGross: 0,
    paymentMethod: 'Überweisung',
    probefahrtDetails: {
      driverName: 'Dr. Michael Weber',
      driverStreet: 'Unter den Linden 42',
      driverPostalCode: '10117',
      driverCity: 'Berlin',
      driverPhone: '+49 171 4455889',
      driverEmail: 'm.weber@charite.de',
      drivingLicenseNumber: 'L82910482B',
      drivingLicenseClasses: 'B, BE, A',
      vin: 'WP0ZZZY1ZMSA48910',
      brand: 'Porsche',
      model: 'Taycan 4S',
      variant: 'Performance Plus',
      color: 'Kreide',
      firstRegistration: '09/2022',
      mileageStart: 18500,
      mileageEnd: 18534,
      fuelLevelStart: '85% (Batterieladung)',
      redLicensePlate: 'B-06124',
      durationMinutes: 30,
      startTime: '14:30',
      expectedReturnTime: '15:00',
      actualReturnTime: '14:58',
      routeLimitKm: 50,
      depositAmount: 0,
      liabilityDeductible: 1000,
      disclaimersAccepted: {
        stvoRules: true,
        noThirdParty: true,
        zeroAlcohol: true,
        deductibleAgreed: true,
        returnOnTime: true,
        trafficFineLiability: true,
        mileageChecked: true
      },
      driverLicenseFile: {
        name: 'Fuehrerschein_Dr_Weber.pdf',
        size: '1.4 MB',
        type: 'PDF'
      },
      place: 'Berlin',
      date: '15.08.2026'
    },
    notes: 'Probefahrt Avus Süd & Stadtverkehr. Fahrzeug einwandfrei ohne Beanstandung zurückgebracht.',
    status: 'abgeschlossen',
    createdAt: '2026-08-15T12:30:00.000Z',
    createdBy: 'Stefan Becker'
  },
  {
    id: 'op-uep-1002',
    documentType: 'uebergabeprotokoll',
    documentNumber: 'UEP2608-1002',
    date: '14.08.2026',
    kundeId: 'cust-2',
    customer: {
      id: 'cust-2',
      type: 'B2C',
      name: 'Sarah Lindemann',
      salutation: 'Frau',
      email: 'sarah.lindemann@web.de',
      phone: '+49 160 9988771',
      street: 'Bergmannstraße 19',
      city: 'Berlin',
      postalCode: '10961',
      country: 'Deutschland',
      purchasesCount: 1,
      totalSpent: 35900,
      lastContact: '14.08.2026'
    },
    isManualCustomer: false,
    autoId: 'veh-1',
    vehicles: [
      {
        id: 'veh-item-2',
        vehicleId: 'veh-1',
        vin: 'WBA31AY080FK92184',
        brand: 'BMW',
        model: '320d xDrive M Sport',
        variant: 'Touring Aut. Laser Head-Up Pano',
        firstRegistration: '05/2023',
        mileage: 28400,
        powerPs: 190,
        powerKw: 140,
        fuelType: 'Diesel',
        color: 'Mineralgrau Metallic',
        listPrice: 35900,
        sellingPrice: 35900,
        discountAmount: 0,
        taxType: 'diff_25a'
      }
    ],
    totalNet: 35900,
    totalTax: 0,
    totalGross: 35900,
    paymentMethod: 'Überweisung',
    uebergabeprotokollDetails: {
      protocolDate: '14.08.2026',
      protocolTime: '11:15',
      sellerName: 'Stefan Becker',
      sellerCompany: 'MaxFleet Autohandel GmbH',
      sellerPhone: '+49 30 8920100',
      buyerName: 'Sarah Lindemann',
      buyerPhone: '+49 160 9988771',
      buyerStreet: 'Bergmannstraße 19',
      buyerPostalCode: '10961',
      buyerCity: 'Berlin',
      driverLicenseNumber: 'B08819401P',
      vin: 'WBA31AY080FK92184',
      brand: 'BMW',
      model: '320d xDrive M Sport',
      variant: 'Touring Aut.',
      licensePlate: 'B-SL 2026',
      color: 'Mineralgrau Metallic',
      firstRegistration: '05/2023',
      powerPs: 190,
      powerKw: 140,
      fuelType: 'Diesel',
      mileage: 28400,
      fuelLevel: '100% (Voll)',
      keysCount: 2,
      externalInspection: {
        bumperFront: { status: 'ok' },
        bumperRear: { status: 'ok' },
        grille: { status: 'ok' },
        hood: { status: 'ok' },
        fendersFront: { status: 'ok' },
        fendersRear: { status: 'ok' },
        doorsLeft: { status: 'ok' },
        doorsRight: { status: 'ok' },
        pillars: { status: 'ok' },
        roof: { status: 'ok' },
        trunkLid: { status: 'ok' },
        windshield: { status: 'ok' },
        sideRearWindows: { status: 'ok' },
        headlights: { status: 'ok' },
        taillightsTurnSignals: { status: 'ok' }
      },
      tires: {
        tireType: 'Sommer',
        frontLeftMm: 6.2,
        frontRightMm: 6.1,
        rearLeftMm: 6.8,
        rearRightMm: 6.7,
        spareWheel: 'Pannenset',
        rimsCondition: 'ok',
        rimType: 'Alufelgen'
      },
      interiorInspection: {
        seatsUpholstery: { status: 'ok' },
        steeringWheel: { status: 'ok' },
        dashboardCockpit: { status: 'ok' },
        infotainmentNavi: { status: 'ok' },
        airConditioning: { status: 'ok' },
        heatingVentilation: { status: 'ok' },
        seatbelts: { status: 'ok' },
        floorMats: { status: 'ok' },
        headliner: { status: 'ok' },
        mirrors: { status: 'ok' }
      },
      additionalEquipment: {
        keysCountCheck: { present: true, count: 2, status: 'ok' },
        centralLocking: { present: true, status: 'ok' },
        powerWindows: { present: true, status: 'ok' },
        sunroof: { present: true, status: 'ok' },
        parkingSensorsPdc: { present: true, status: 'ok' },
        backupCamera: { present: true, status: 'ok' },
        secondTireSet: { present: true, status: 'ok' },
        firstAidWarningTriangle: { present: true, status: 'ok' },
        onboardTools: { present: true, status: 'ok' }
      },
      mechanicalInspection: {
        engineStartIdle: { status: 'ok' },
        transmissionGearbox: { status: 'ok' },
        clutch: { status: 'ok' },
        brakesHandbrake: { status: 'ok' },
        steeringHandling: { status: 'ok' },
        suspensionShockAbsorbers: { status: 'ok' },
        exhaustSystem: { status: 'ok' },
        oilCoolantLevels: { status: 'ok' },
        starterBattery: { status: 'ok' },
        cockpitWarningLights: { status: 'ok' }
      },
      damagePoints: [
        {
          id: 'dmg-sample-1',
          view: 'side_left',
          x: 72,
          y: 44,
          category: 'D1',
          title: 'Mikrokratzer Türkante',
          description: 'Mikrokratzer Türkante hinten links (poliert)'
        }
      ],
      associatedDocuments: {
        huValidityDate: '05/2026',
        hasKfzBrief: true,
        hasKfzSchein: true,
        hasServiceBook: true,
        hasCoCDocument: true,
        hasPreviousInvoice: true,
        hasDeregistrationDoc: true,
        hasManuals: true
      },
      photoAttachments: [],
      generalNotes: 'Fahrzeug vollständig aufbereitet und mit 8-fach Bereifung an die Kundin übergeben. Einweisung in iDrive und Assistenzsysteme erfolgt.',
      receiptDeclarationConfirmed: true,
      place: 'Berlin',
      handoverDate: '14.08.2026'
    },
    notes: 'Kundenübergabe erfolgreich abgeschlossen.',
    status: 'abgeschlossen',
    createdAt: '2026-08-14T09:15:00.000Z',
    createdBy: 'Stefan Becker'
  }
];

